[package]
name = "journaling"
version = "0.1.0"
authors = ["Louis Bui <louisbui2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1.3.9"
rand = "0.7.3"